name = "tacint-masterserver"
main = "src/index.ts"
compatibility_date = "2023-12-18"


# NO SECRETS HERE:
[vars]


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "tacint-ms-db"
database_id = "b4cc5ca9-dd91-4680-ab1f-8120fab768b9"


[triggers]
# Schedule cron triggers:
# - Every 20 minutes
crons = [ "*/20 * * * *" ]
